### ISSUE TITLE
 unexpected identifier `build-runtime', expected value

### ISSUE THREAD

**Issue by gBopHuk** [winepak/winepak-sdk-images#19]
Can't build repo by a guide from main page - https://github.com/winepak/winepak-sdk-images :

```
$ flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
$ flatpak install flathub org.freedesktop.Sdk
$ flatpak install flathub org.freedesktop.Platform
$ git clone https://github.com/winepak/winepak-sdk-images.git
$ cd winepak-sdk-images
$ flatpak-builder --arch=i386 --ccache --keep-build-dirs --force-clean --repo=winepak-repo builds/winepak-sdk-images-i386 org.winepak.Sdk.yml

Can't parse 'org.winepak.Sdk.yml': <data>:1:13: Parse error: unexpected identifier `build-runtime', expected value
```

**Comment by gBopHuk** [comment]
I used flatpak 0.9.7. I checked in flatpak 0.11.8. NO any  "parse" erros. Seems it was a problem.

**Comment by gBopHuk** [comment]
Ubuntu/18.04 with 
flatpak-0.11.7-0ubuntu0.1
flatpak-builder-0.10.9-1
gir1.2-flatpak-1.0-0.11.7-0ubuntu0.1
libflatpak0-0.11.7-0ubuntu0.1


The problem is reproduced too

**Comment by julianrichen** [comment]
We exclusively use yaml files instead of json, yaml wasn't a feature in `flatpak-builder` till version `0.10.10`:

https://github.com/flatpak/flatpak-builder/releases/tag/0.10.10
> Major changes in 0.10.10
> - We now support yaml manifest as well as json.

You'll need to update to build the files from source, or use the repo from https://www.winepak.org
