### ISSUE TITLE
Version to be chosen

### ISSUE THREAD

**Issue by Sayanel01** [winepak/winepak-sdk-images#36]
When I run `flatpak install flathub org.freedesktop.Sdk` or `flatpak install flathub org.freedesktop.Platform` I get the message : 
`error: Multiple branches available for org.freedesktop.Platform, you must specify one of: org.freedesktop.Platform//1.6, org.freedesktop.Platform//18.08`

so `flatpak install flathub org.freedesktop.Platform//18.08` works, but I have no idea why I should chose one or the other. 
How to choose ? And could the install instruction be updated ?

**Comment by ideologysec** [comment]
18.08 is the current development/newest branch. I'm unclear on what winepak recommends.

**Comment by julianrichen** [comment]
The sdk & platform in master targets 1.6 but that is very out of date. New versions need to be built.

Closing as this will be addressed in other issues.
